sno=int(input ('enter student no:'))
name=input('enter name:')
group=input ('enter group:')
gender=input('enter gender:')
address=input ('enter address:')
phoneno=int(input ('enter phoneno:'))
print('sno:',sno)
print('name:',name)
print('group:', group)
print('gender:',gender)
print('address:',address)
print('phoneno:', phoneno)
